name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build-android64:
    name: Android64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          configure-args: -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_FLAGS=-DFMT_USE_CONSTEVAL=0

  build-android32:
    name: Android32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android32
          configure-args: -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_FLAGS=-DFMT_USE_CONSTEVAL=0

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          configure-args: -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_FLAGS=-DFMT_USE_CONSTEVAL=0
